services:
  mysql:
    image: mysql:8.0
    container_name: example_mysql
    restart: always
    ports:
      - "33306:3306"
    volumes:
      - ./db/mysql/data:/var/lib/mysql
      - ./db/mysql/init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: example
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_unicode_ci
      TZ: Asia/Seoul
